<<<<<<< HEAD
version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: hotel_db_container
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${PG_USER:-user}
      POSTGRES_PASSWORD: ${PG_PASS:-password}
      POSTGRES_DB: ${PG_DB:-hotel_bookings_db}
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
    driver: local
=======
version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: hotel_pg
    restart: always
    environment:
      POSTGRES_DB: hotel_db
      POSTGRES_USER: pipeline_user
      POSTGRES_PASSWORD: supersecretpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pipeline_user -d hotel_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hotel_pipeline
    depends_on:
      postgres:
        condition: service_healthy

    env_file:
      - ./config/.env

    volumes:
      - .:/app
      - ./config/.env:/app/config/.env

    working_dir: /app

    command: ["sleep", "infinity"]

volumes:
  pgdata:
>>>>>>> 21ff55e155f3eb9ee2ad79805daf749db3d71516
